# Generated by Django 2.1.5 on 2019-01-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gast',
            name='anrede',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gast',
            name='vorname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
