# Generated by Django 2.1.5 on 2019-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw', '0002_auto_20190122_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gast',
            name='anrede',
            field=models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Familie', 'Familie'), ('Mr.', 'Mister'), ('Mrs.', 'Miss')], max_length=20, null=True),
        ),
    ]
