# Generated by Django 2.1.5 on 2019-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw', '0004_auto_20190122_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gast',
            name='anrede',
            field=models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Familie', 'Familie'), ('Mr.', 'Mister'), ('Mrs.', 'Miss')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gast',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gast',
            name='vorname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
