# Generated by Django 2.1.5 on 2019-01-22 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fw', '0005_auto_20190122_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_von', models.DateField(blank=True, null=True)),
                ('datum_bis', models.DateField(blank=True, null=True)),
                ('preis', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('kosten_chiara', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('anzahl_gaeste', models.IntegerField(default=2, max_length=3)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('gast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fw.Gast')),
            ],
            options={
                'verbose_name_plural': 'buchungen',
            },
        ),
    ]
