# Generated by Django 2.1.5 on 2019-01-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fw', '0006_buchung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='anzahl_gaeste',
            field=models.IntegerField(default=2),
        ),
    ]
